import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import { InitiativesView } from "../src/components/initiatives/InitiativesView"
import { getRootContainer } from "../src/services/_root-container"
import { InitiativesDTO } from "../src/services/charity-data"

export const getStaticProps = async (context) => {
  const root = getRootContainer()
  const initiativesDataDTO = await root.containers.initiativesDataDTO
  return {
    props: {
      initiativesDataDTO,
    },
  }
}
interface InitiativesPageProps {
  initiativesDataDTO: InitiativesDTO[]
}

const InitiativesList: NextPage<InitiativesPageProps> = ({
  initiativesDataDTO,
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Initiatives List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <InitiativesView initiativesDataDTO={initiativesDataDTO} />
      </main>
    </div>
  )
}

export default InitiativesList
